---
- name: Install and configure Apache with Laravel and MariaDB
  hosts: all
  gather_facts: true
  become: true
  vars:
    db_host: "{{ db_host | default('localhost') }}"
    db_name: "{{ db_name | default('app_db') }}"
    db_user: "{{ db_user | default('app_user') }}"
    db_pass: "{{ db_pass | default('app_pass') }}"
    mariadb_root_password: "rootpass"  # Локальный пароль для root
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - mariadb-server
          - python3-pymysql
          - apache2
          - php
          - php-mysql
          - unzip
          - curl
          - php-xml
          - php-cli
          - php-mbstring
          - composer
        state: present
        update_cache: yes

    - name: Ensure services are running and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mariadb

    - name: Configure MariaDB root user for password-based login
      block:
        - name: Check MariaDB root authentication plugin
          command: mysql -u root -e "SELECT plugin FROM mysql.user WHERE user='root' AND host='localhost';"
          register: mariadb_auth_plugin

        - name: Update root user authentication to password-based
          command: |
            mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password }}'; FLUSH PRIVILEGES;"
          when: "'auth_socket' in mariadb_auth_plugin.stdout"

        - name: Switch to mysql_native_password if needed
          command: |
            mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mariadb_root_password }}'; FLUSH PRIVILEGES;"
          when: "'mysql_native_password' not in mariadb_auth_plugin.stdout"

    - name: Create application database
      mysql_db:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: "{{ db_name }}"
        state: present

    - name: Create application user
      mysql_user:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL"
        host: "%"
        state: present

    - name: Clone Laravel application
      git:
        repo: https://github.com/Practical-DevOps/app-for-devops.git
        dest: /var/www/html/app-for-devops
        force: yes

    - name: Set permissions for Laravel application
      file:
        path: /var/www/html/app-for-devops
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Configure .env file
      lineinfile:
        path: /var/www/html/app-for-devops/.env
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop:
        - { key: 'DB_HOST', value: '{{ db_host }}' }
        - { key: 'DB_DATABASE', value: '{{ db_name }}' }
        - { key: 'DB_USERNAME', value: '{{ db_user }}' }
        - { key: 'DB_PASSWORD', value: '{{ db_pass }}' }

    - name: Install Laravel dependencies using Composer
      command: composer install
      args:
        chdir: /var/www/html/app-for-devops

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: /var/www/html/app-for-devops

      args:
        chdir: "{{ app_dir }}"
