---
- name: Install and configure Laravel dependencies
  hosts: all
  gather_facts: false
  become: true
  vars:
    app_dir: /var/www/html/app-for-devops
  tasks:
    - name: Install required packages
      apt:
        name:
          - php
          - php-mysql
          - unzip
          - curl
          - composer
          - mariadb-client
          - nodejs
          - npm
        state: present

    - name: Clone Laravel application
      git:
        repo: https://github.com/Practical-DevOps/app-for-devops.git
        dest: "{{ app_dir }}"
        force: yes

    - name: Set permissions for Laravel application
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Copy .env.example to .env
      copy:
        src: "{{ app_dir }}/.env.example"
        dest: "{{ app_dir }}/.env"

    - name: Update .env with database configurations
      lineinfile:
        path: "{{ app_dir }}/.env"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop:
        - { key: 'DB_HOST', value: '{{ db_host }}' }
        - { key: 'DB_DATABASE', value: '{{ db_name }}' }
        - { key: 'DB_USERNAME', value: '{{ db_user }}' }
        - { key: 'DB_PASSWORD', value: '{{ db_pass }}' }

    - name: Install Laravel dependencies using Composer
      command: composer install
      args:
        chdir: "{{ app_dir }}"
        creates: "{{ app_dir }}/vendor/autoload.php"

    - name: Generate Laravel application key
      command: php artisan key:generate
      args:
        chdir: "{{ app_dir }}"

    - name: Run database migrations
      command: php artisan migrate --force
      args:
        chdir: "{{ app_dir }}"
