---
- name: Install and configure Apache with Laravel and MariaDB
  hosts: all
  gather_facts: true
  become: true
  vars:
    db_host: "localhost"
    app_dir: /var/www/html/app-for-devops
    mariadb_root_password: rootpass  # Change as needed
    db_name: lrv
    db_user: lrv
    db_pass: lrvpass  # Change as needed
  tasks:
    - name: Install required packages
      apt:
        name: 
          - python3
          - python3-pip
          - mariadb-server
          - python3-pymysql
          - apache2
          - php
          - php-mysql
          - unzip
          - curl
          - php-xml
          - php-cli
          - php-mbstring
          - composer
        state: present
        update_cache: yes

    - name: Ensure services are running and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mariadb

    - name: Secure MariaDB installation
      mysql_user:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        host: "{{ db_host }}"
        priv: "{{ db_name }}.*:ALL"
        state: present

    - name: Clone Laravel application
      git:
        repo: https://github.com/Practical-DevOps/app-for-devops.git
        dest: "{{ app_dir }}"
        force: yes

    - name: Set permissions for Laravel application
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Configure .env file
      lineinfile:
        path: "{{ app_dir }}/.env"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop:
        - { key: 'DB_HOST', value: '{{ db_host }}' }
        - { key: 'DB_DATABASE', value: '{{ db_name }}' }
        - { key: 'DB_USERNAME', value: '{{ db_user }}' }
        - { key: 'DB_PASSWORD', value: '{{ db_pass }}' }

    - name: Install Laravel dependencies using Composer
      command: composer install
      args:
        chdir: "{{ app_dir }}"
      register: composer_output

    - name: Run Laravel migrations
      command: php artisan migrate --force
      args:
        chdir: "{{ app_dir }}"

