name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_NAME: lrv
      DB_USER: lrv
      DB_PASS: lrvpass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt and install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip ufw mariadb-client

      - name: Setup Ansible
        run: python3 -m pip install --user ansible

      - name: Set masked outputs
        run: |
          echo "::add-mask::$DB_HOST"
          echo "::add-mask::$DB_NAME"
          echo "::add-mask::$DB_USER"
          echo "::add-mask::$DB_PASS"

      - name: Generate Ansible inventory file
        run: |
          cat << EOF > hosts
          [server]
          localhost ansible_connection=local
          [db]
          localhost ansible_connection=local
          EOF

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ./hosts main.yml -e "db_host=$DB_HOST db_name=$DB_NAME db_user=$DB_USER db_pass=$DB_PASS" -c local

      - name: Verify MariaDB connection
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e "USE $DB_NAME; SHOW TABLES;"

      - name: Test application with Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./.github/tests

      - name: Validate application setup
        run: |
          curl -s http://localhost | grep -i "Laravel" || exit 1

